spring:
  config:
    activate:
      on-profile: default
  application:
    name: "test-service"
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate.show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"